// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6TtenBHOjxbfsWULV8YDg_gZOTpzgMz0',
    appId: '1:714425269281:web:5ba1b29483544ab735f760',
    messagingSenderId: '714425269281',
    projectId: 'appcarrental-45f7e',
    authDomain: 'appcarrental-45f7e.firebaseapp.com',
    storageBucket: 'appcarrental-45f7e.firebasestorage.app',
    measurementId: 'G-SPPG33H62L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7iyA3SQnoRa-VizaQgPcTQGcZ40I9Hjs',
    appId: '1:714425269281:android:03e971b5f86dda9f35f760',
    messagingSenderId: '714425269281',
    projectId: 'appcarrental-45f7e',
    storageBucket: 'appcarrental-45f7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtrRe-mTJzTLkkz3dB-p24yw51_Ioi01Y',
    appId: '1:714425269281:ios:8ec7d76ab7d784b635f760',
    messagingSenderId: '714425269281',
    projectId: 'appcarrental-45f7e',
    storageBucket: 'appcarrental-45f7e.firebasestorage.app',
    iosBundleId: 'com.example.appCarRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtrRe-mTJzTLkkz3dB-p24yw51_Ioi01Y',
    appId: '1:714425269281:ios:8ec7d76ab7d784b635f760',
    messagingSenderId: '714425269281',
    projectId: 'appcarrental-45f7e',
    storageBucket: 'appcarrental-45f7e.firebasestorage.app',
    iosBundleId: 'com.example.appCarRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6TtenBHOjxbfsWULV8YDg_gZOTpzgMz0',
    appId: '1:714425269281:web:757f4d4bcbdd6af135f760',
    messagingSenderId: '714425269281',
    projectId: 'appcarrental-45f7e',
    authDomain: 'appcarrental-45f7e.firebaseapp.com',
    storageBucket: 'appcarrental-45f7e.firebasestorage.app',
    measurementId: 'G-BJNWJGGX2G',
  );
}
