// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYxNVH7Y1tsBen9MBNxu4HLbmq7Sr68Mc',
    appId: '1:1026020249155:web:1da8d1a6f6dfc4837a0ef6',
    messagingSenderId: '1026020249155',
    projectId: 'appcarrent-ec455',
    authDomain: 'appcarrent-ec455.firebaseapp.com',
    storageBucket: 'appcarrent-ec455.firebasestorage.app',
    measurementId: 'G-CG9G13M7HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFlF4m0Igpj_yrdZz9RpWYn1XCEGmRCQ',
    appId: '1:1026020249155:android:d2c316c7a3da8c667a0ef6',
    messagingSenderId: '1026020249155',
    projectId: 'appcarrent-ec455',
    storageBucket: 'appcarrent-ec455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJFeT07ceHPXlB1QeAK_QsFwK21bo3emw',
    appId: '1:1026020249155:ios:ba8aad4a6c6fb09b7a0ef6',
    messagingSenderId: '1026020249155',
    projectId: 'appcarrent-ec455',
    storageBucket: 'appcarrent-ec455.firebasestorage.app',
    iosBundleId: 'com.example.appCarRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJFeT07ceHPXlB1QeAK_QsFwK21bo3emw',
    appId: '1:1026020249155:ios:ba8aad4a6c6fb09b7a0ef6',
    messagingSenderId: '1026020249155',
    projectId: 'appcarrent-ec455',
    storageBucket: 'appcarrent-ec455.firebasestorage.app',
    iosBundleId: 'com.example.appCarRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYxNVH7Y1tsBen9MBNxu4HLbmq7Sr68Mc',
    appId: '1:1026020249155:web:d394ea66b9bae3467a0ef6',
    messagingSenderId: '1026020249155',
    projectId: 'appcarrent-ec455',
    authDomain: 'appcarrent-ec455.firebaseapp.com',
    storageBucket: 'appcarrent-ec455.firebasestorage.app',
    measurementId: 'G-9G4G3S946N',
  );

}